#ifndef _SAUCECODE_SHOTGUNS_PACKETID_HPP
#define _SAUCECODE_SHOTGUNS_PACKETID_HPP

const unsigned char PACKET_CONNECT = 0,
	PACKET_DISCONNECT = 1,
	PACKET_ADD_PLAYER = 2,
	PACKET_DROP_PLAYER = 3,
	PACKET_MOVE_PLAYER = 4;

#endif
